dinov2:
  name: dinov2_vitl14
  checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"

compvit:
  name: compvitb14
  # checkpoint: "/scratch/gilbreth/pjajal/dinov2_vitl14_pretrain.pth"
  checkpoint: "/scratch/gilbreth/pjajal/checkpoints-again/distill_2024-03-27-100154/best_performing.pth"

head:
  num_classes: 1000
  checkpoint: ""


hyperparameters:
  lr: 1.0E-04
  min_lr: 1.0e-7
  warmup_lr_scale: 1.0e-4
  warmup_epochs: 2
  batch_size: 512
  test_batch_size: 32
  num_workers: 16
  epochs: 75
  mixup_alpha: 0.8 
  accumulations: 2
  in_memory: False
  gradient_clip_val: 1.5

args:
  device: cuda:0
  data_dir_train: "/scratch/gilbreth/pjajal/datasets/train_500_0.5_90.ffcv"
  data_dir_test: "/scratch/gilbreth/pjajal/datasets/val_500_0.5_90.ffcv"
  data_dir: "/scratch/gilbreth/pjajal/datasets/imagenet-1k"
  precision: "bf16-mixed"