dinov2:
  name: dinov2_vitl14
  checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"

compvit:
  name: compvitl14
  # checkpoint: "/scratch/gilbreth/pjajal/dinov2_vitl14_pretrain.pth"
  checkpoint: "/scratch/gilbreth/pjajal/checkpoints/mae_2024-03-09-132303/best_performing.pth"

head:
  num_classes: 1000
  checkpoint: ""


hyperparameters:
  lr: 1.0E-03
  min_lr: 1.0e-6
  warmup_lr_scale: 1.0e-4
  warmup_epochs: 5
  batch_size: 512
  test_batch_size: 32
  num_workers: 32
  epochs: 150
  mixup_alpha: 0.8 
  accumulations: 1
  in_memory: False
  gradient_clip_val: 1.0

args:
  device: cuda:0
  data_dir_train: "/scratch/gilbreth/pjajal/datasets/train_500_0.5_90.ffcv"
  data_dir_test: "/scratch/gilbreth/pjajal/datasets/val_500_0.5_90.ffcv"
  data_dir: "/scratch/gilbreth/pjajal/datasets/imagenet-1k"
  precision: "bf16-mixed"